version: "2"
services:
  oss:
    container_name: oss
    image: docker.pkg.github.com/tonywangcn/git-oss/git-oss:prod
    working_dir: /app
    privileged: True
    env_file: prod.env
    ports:
      - "8000:8000"
    # command: ["tail", "-f", "/dev/null"]
    command: "python main.py"
